### ISSUE TITLE
Update dotNet Core sdk to v3.0

### ISSUE THREAD

**Issue by bogdancice** [nosinovacao/dotnet-sonar#11] opened 2019-09-30 15:20 UTC
Update dotNet Core sdk to v3.0

tag: mcr.microsoft.com/dotnet/core/sdk:3.0

**Comment by NazmiAltun** [comment] 2019-10-20 06:49
sonar-scanner  still depends on  2.x SDK  at the moment. I was facing missing 2.x SDK issue .In order to fix it i had to  run the command with --roll-forward Major  option. Like ;
`dotnet --roll-forward Major /sonar-scanner/SonarScanner.MSBuild.dll   begin ....`

**Comment by cocode32** [comment] 2019-10-22 14:36
@NazmiAltun - Thank you so much for this! I thought I was going crazy, but I'm glad this is an actual problem with the image. Using your suggested command works as expected and can now be used! I hope this will be resolved in the actual image soon. As far as I can understand, it simply needs dotnet core 2 and 3 to be installed into the image for this to be fixed? Anyway, thanks for the command

**Comment by NazmiAltun** [comment] 2019-10-22 15:06
@NewteqDeveloper  it has nothing to do with the image. It is because  sonar-scanner tool still depends on .net core 2 and  .net core version in the image is  v3.
You can actually follow the isssue in sonar-scanner github page.  One work around is that to install .netcore  2.x version in the image and have both versions. Or better ,  just  run the command with the  suggested flag  and avoid bloating the  image with 2  different versions of  .netcore .

**Comment by gafda** [comment] 2019-10-30 11:51
SonarScanner v4.7.1.2311 was built for DotNetCore v2.1 and it does not work with DotNetCore v3 only.

We're are currently working on a solution and will release it as soon as possible.

Duplicate of #13

**Comment by gafda** [comment] 2019-10-31 11:16
A new image was created that additionally includes the DotNetCore v2.2.7 to be able to execute the SonarScanner.

See on #13

**Closed as completed by gafda** 2019-10-31 11:16 UTC
